### PR TITLE
Jython integration

### PR DESCRIPTION
**Pull request by jsark**
Here are the changes for jython integration. Let me know if you have any questions or comments.

### CODE REVIEW

**Comment by stefangs** [comment]
Really clean and nice integration! Two questions: 
1) Is it ok if I add the standard copyright file header from the project on the python.java-file, I really want to have exactly the same license conditions for all source in the core. I will of course add a separate comment attributing you for contributing the file.
2) Don't you think we need to synchronize the call to "callFunction()"? I am not sure these calls are thread safe, and multiple Items could call this at the same time.

**Comment by jsark** [comment]
Thanks!
1) Sure, no problem. 
2) Good point. Yes, it is better to synchronize the call, if there is a chance of multiple threads calling the function at the same. I don't think "exec()" and "compile()" are thread safe in jython.

**Comment by stefangs** [comment]
I have done some changes to the code now: I had to change to jython-standalone jar, otherwise it needed external packages to work. Instead of interpreting the command in the Item as a function name, I just execute it as python code. This means it can be a function call, or it can be any Python code. It made the code simpler and the feature more generic. I also use the interpreter to compile the Jython code and do not reinterpret the file for each function call. I synchronized the calls to the Python class. The feature seems to work great!

**Comment by SourceCodeSourcerer** [comment]
Stefan, it's christmas... Just saying! Merry Christmas!

Skickat från en iPhone

**Comment by jsark** [comment]
Nice changes! 
I especially like how streamlined and simple the Python class is now!

**Pull request merged**
